DataSet.key_name = name
DataSource.key_name = name
Allele.key_primaryidentifier = primaryIdentifier
Gene.key_primaryidentifier = primaryIdentifier
OntologyTerm.key_identifier = identifier
Publication.key_pubmedid = pubMedId
PhenotypeAnnotation.key_allele_term = alleleSubject, ontologyTerm
