DataSet.key_name = name
DataSource.key_name = name
Organism.key_taxonid = taxonId
Allele.key_primaryidentifier = primaryIdentifier, organism
DOTerm.key_identifier = identifier
ECOTerm.key_identifier = identifier
Publication.key_pubmedid = pubMedId
DiseaseAnnotation.key_allele_term = alleleSubject, ontologyTerm
