DataSet.key_name = name
DataSource.key_name = name
Organism.key_taxonid = taxonId
Gene.key_primaryidentifier = primaryIdentifier, organism
Strain.key_id = primaryIdentifier
Publication.key_pubmedid = pubMedId
RNAi.key_id = primaryIdentifier
