DataSet.key_name = name
DataSource.key_name = name
Organism.key_taxonid = taxonId
Gene.key_primaryidentifier = primaryIdentifier, organism
OntologyTerm.key_identifier = identifier
DOTerm.key_identifier = identifier
ECOTerm.key_identifier = identifier
Publication.key_pubmedid = pubMedId
DiseaseAnnotation.key_subject_term = subject, ontologyTerm
