DataSet.key_name = name
DataSource.key_name = name
Organism.key_taxonid = taxonId
Allele.key_primaryidentifier = primaryIdentifier, organism
Gene.key_primaryidentifier = primaryIdentifier, organism
SOTerm.key_identifier = identifier
Variant.key_id = primaryIdentifier
VariantConsequence.key_var_name = variant, consequenceCode
