DataSet.key_name = name
DataSource.key_name = name
Organism.key_taxonid = taxonId
OntologyTerm.key_identifier = identifier
Publication.key_pubmedid = pubMedId
Sample.key_primaryidentifier = primaryIdentifier
